version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:18.0.2'
    steps:
      - checkout
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud