version: 2.1

jobs:
  build_and_test:
    parallelism: 1
    
    docker:
      - image: cimg/base:2021.04

    steps:
      - checkout
      - run: wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip && unzip sonar-scanner-cli-3.2.0.1227-linux.zip

workflows:
  version: 2

  build_and_test:
    jobs:
      - build_and_test