version: 2.1

jobs:
  build:
    docker:
      - image: 'ubuntu:latest'
    -run:
      sudo apt install curl -y
    steps:
      - checkout
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud