version: 2.1

executors:
  scanner:
    docker:
      - image: cimg/base:2022.09

commands:
  check-code-quality:
    description: Check Code Quality

    steps:
      - checkout
      - run: export SONAR_SCANNER_VERSION=4.7.0.2747
      - run: export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - run: curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - run: unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - run: export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - run: export SONAR_SCANNER_OPTS="-server"
      - run: sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
      - run: sonar-scanner \
             -Dsonar.organization=anchaubey \
             -Dsonar.projectKey=anchaubey_terraformapi_gw \
             -Dsonar.sources=. \
             -Dsonar.host.url=https://sonarcloud.io
             -Dsonar.login=57846888475a2cd4350f15c88b7dc1f75d406f99

jobs:
  check-code-job:
    executor: scanner
    steps:
     - check-code-quality

workflows:
  check-code-quality-flow:
    jobs:
      - check-code-job:
          context: lineclass